/**
 * site_selector.js — AUTO-GENERATED by classify_dataset_urls.py
 *
 * All URLs are BENIGN entries from malicious_phish.csv, classified
 * into personas by domain + path keyword matching.
 *
 * Dead-URL blacklist: URLs that returned Chrome error pages are persisted
 * to chrome.storage.local under 'deadUrls' and permanently excluded.
 *
 * Re-generate dataset pool any time:  python classify_dataset_urls.py
 */

// ── Guaranteed-safe fallback URLs (Wikipedia/MDN) ─────────────────────────
// These are used for the CURRENT noise cycle when a dataset URL fails.
// They never go dead and the ML model always classifies them as LOW risk.
const FALLBACK_URLS = {
    tech: [
        'https://en.wikipedia.org/wiki/Artificial_intelligence',
        'https://en.wikipedia.org/wiki/Machine_learning',
        'https://en.wikipedia.org/wiki/Computer_science',
        'https://en.wikipedia.org/wiki/Open-source_software',
        'https://en.wikipedia.org/wiki/Cloud_computing',
        'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
        'https://developer.mozilla.org/en-US/docs/Web/HTML',
        'https://en.wikipedia.org/wiki/Cybersecurity',
        'https://en.wikipedia.org/wiki/Quantum_computing',
        'https://en.wikipedia.org/wiki/Python_(programming_language)',
    ],
    health: [
        'https://en.wikipedia.org/wiki/Nutrition',
        'https://en.wikipedia.org/wiki/Physical_fitness',
        'https://en.wikipedia.org/wiki/Mental_health',
        'https://en.wikipedia.org/wiki/Meditation',
        'https://en.wikipedia.org/wiki/Sleep_hygiene',
        'https://en.wikipedia.org/wiki/Immune_system',
        'https://en.wikipedia.org/wiki/Yoga',
        'https://en.wikipedia.org/wiki/Gut_microbiota',
        'https://en.wikipedia.org/wiki/Mindfulness',
        'https://en.wikipedia.org/wiki/Cardiovascular_disease',
    ],
    finance: [
        'https://en.wikipedia.org/wiki/Personal_finance',
        'https://en.wikipedia.org/wiki/Index_fund',
        'https://en.wikipedia.org/wiki/Compound_interest',
        'https://en.wikipedia.org/wiki/Inflation',
        'https://en.wikipedia.org/wiki/Stock_market',
        'https://en.wikipedia.org/wiki/Exchange-traded_fund',
        'https://en.wikipedia.org/wiki/Mutual_fund',
        'https://en.wikipedia.org/wiki/Tax',
        'https://en.wikipedia.org/wiki/Budget',
        'https://en.wikipedia.org/wiki/Retirement_savings_account',
    ],
    travel: [
        'https://en.wikipedia.org/wiki/Tourism',
        'https://en.wikipedia.org/wiki/Adventure_travel',
        'https://en.wikipedia.org/wiki/Backpacking_(travel)',
        'https://en.wikipedia.org/wiki/National_park',
        'https://en.wikipedia.org/wiki/World_Heritage_Site',
        'https://en.wikipedia.org/wiki/Ecotourism',
        'https://en.wikipedia.org/wiki/Bali',
        'https://en.wikipedia.org/wiki/Iceland',
        'https://en.wikipedia.org/wiki/Travel_visa',
        'https://en.wikipedia.org/wiki/Hostel',
    ],
    news: [
        'https://en.wikipedia.org/wiki/Journalism',
        'https://en.wikipedia.org/wiki/Freedom_of_the_press',
        'https://en.wikipedia.org/wiki/Climate_change',
        'https://en.wikipedia.org/wiki/Renewable_energy',
        'https://en.wikipedia.org/wiki/Space_exploration',
        'https://en.wikipedia.org/wiki/Human_rights',
        'https://en.wikipedia.org/wiki/Democracy',
        'https://en.wikipedia.org/wiki/Education',
        'https://en.wikipedia.org/wiki/Biodiversity',
        'https://en.wikipedia.org/wiki/Global_warming',
    ],
};

export const SiteSelector = {
    // ── Dataset URL pools (auto-generated) ───────────────────────────────────
    sites: {
        // ── TECH persona ────────────────────────────────────────────────────
        tech: [
            'http://techcrunch.com/video/day-one-recap-with-anthony-ha-colleen-taylor-mike-butcher/518806779/',
            'http://stackoverflow.com/questions/30194208/is-a-string-an-array-in-vba-that-can-be-iterated-through',
            'http://stackoverflow.com/questions/24915277/rails-app-nginx-passenger-freezes-up-for-20-minutes',
            'http://stackoverflow.com/questions/4728285/the-request-was-aborted-could-not-create-ssl-tls',
            'https://arstechnica.com/information-technology/2015/05/why-ive-abandoned-ubuntu-for-osx/',
            'https://thenextweb.com/apps/2015/05/12/firefox-38-brings-ui-tweaks-on-android/',
            'https://techcrunch.com/2015/05/12/google-io-2015-keynote/',
            'https://arstechnica.com/tech-policy/2015/05/movie-studios-appeal-hotfile-judgment/',
            'http://stackoverflow.com/questions/4296990/removing-object-from-collection-in-loop',
            'http://stackoverflow.com/questions/6592830/ajax-call-doesnt-work-in-firefox',
            'https://thenextweb.com/insider/2015/05/12/apple-passes-100m-monthly-listeners/',
            'http://stackoverflow.com/questions/22049030/jquery-bootstrap-tooltip-not-working',
            'http://stackoverflow.com/questions/2386714/counting-items-in-a-collection-where',
            'http://stackoverflow.com/questions/18522894/getting-value-of-select-box-in-javascript',
            'http://stackoverflow.com/questions/14802654/how-to-find-the-number-of-rows-in-a-query',
            'http://stackoverflow.com/questions/5726988/simple-math-random-in-javascript',
            'https://techcrunch.com/2015/05/11/boxen-meets-the-world/',
            'https://zdnet.com/article/microsoft-edge-browser-details/',
            'https://cnet.com/news/microsoft-edge-browser/',
            'https://arstechnica.com/gadgets/2015/05/samsung-galaxy-s6-edge-review/',
            'https://engadget.com/2015/05/11/facebook-hello/',
            'https://thenextweb.com/apps/2015/05/11/google-now-adds-hotel-price-alerts/',
            'https://slashdot.org/story/15/05/12/003219/microsoft-announces-edge',
            'https://venturebeat.com/2015/05/11/facebook-acquires-theFind/',
            'http://stackoverflow.com/questions/9619172/why-does-object-require-function',
            'https://computerworld.com/article/2919535/browsers/microsoft-edge.html',
            'https://arstechnica.com/information-technology/2015/05/the-state-of-linux/',
            'https://techcrunch.com/2015/05/11/pinterest-visual-search/',
            'http://stackoverflow.com/questions/14802649/how-to-find-the-count-of-records',
            'https://thenextweb.com/dd/2011/05/09/squarespace-to-begin-version-6-beta-testing/',
        ],

        // ── HEALTH persona ───────────────────────────────────────────────────
        health: [
            'https://ncbi.nlm.nih.gov/pubmed/15956633',
            'https://ncbi.nlm.nih.gov/pubmed/18569259',
            'https://ncbi.nlm.nih.gov/pubmed/12548784',
            'https://ncbi.nlm.nih.gov/pubmed/16822960',
            'https://ncbi.nlm.nih.gov/pubmed/17139098',
            'https://ncbi.nlm.nih.gov/pubmed/22219968',
            'https://ncbi.nlm.nih.gov/pubmed/19833985',
            'https://ncbi.nlm.nih.gov/pubmed/23652236',
            'https://healthline.com/nutrition/top-10-evidence-based-health-benefits-of-coconut-oil',
            'https://healthline.com/nutrition/is-fruit-good-or-bad-for-your-health',
            'https://healthline.com/nutrition/20-most-weight-loss-friendly-foods',
            'https://bodybuilding.com/content/the-great-cardio-debate.html',
            'https://bodybuilding.com/content/full-body-training-renaissance.html',
            'https://livestrong.com/article/309089-how-to-make-oatmeal-taste-better/',
            'https://livestrong.com/article/408543-how-to-lose-5-pounds-in-one-week/',
            'https://myfitnesspal.com/food/calories/chicken-breast',
            'https://myfitnesspal.com/recipe/view/8549-avocado-toast',
            'https://medscape.com/viewarticle/844739',
            'https://medscape.com/viewarticle/825066',
            'https://healthgrades.com/physician-directory/reno-nv/',
            'https://webmd.com/diet/obesity/features/how-to-lose-weight-faster',
            'https://webmd.com/fitness-exercise/guide/exercise-for-weight-loss',
            'https://mayoclinic.org/healthy-lifestyle/weight-loss/basics/weightloss-basics/hlv-20049483',
            'https://planoffitness.com/',
            'https://sparkpeople.com/resource/nutrition_articles.asp?id=1547',
            'https://fitday.com/fitness/nutrition/how-to-create-a-fitness-diet-plan.html',
            'https://ncbi.nlm.nih.gov/pubmed/25540980',
            'https://healthline.com/nutrition/how-to-gain-weight',
            'https://bodybuilding.com/content/3-day-workout-routines-for-beginners.html',
            'https://livestrong.com/article/156680-the-benefits-of-yoga-stretching/',
        ],

        // ── FINANCE persona ──────────────────────────────────────────────────
        finance: [
            'https://nasdaq.com/symbol/umbf',
            'https://nasdaq.com/symbol/aapl',
            'https://nasdaq.com/symbol/googl',
            'https://nasdaq.com/symbol/msft',
            'https://nasdaq.com/symbol/amzn',
            'https://forbes.com/sites/greatspeculations/2015/05/12/apple-watch-revenue/',
            'https://forbes.com/sites/billconerly/2015/05/12/should-the-fed-raise-rates/',
            'https://people.forbes.com/profile/warren-buffett/48012',
            'https://bloomberg.com/news/articles/2015-05-12/europe-stocks-rise-as-greek/',
            'https://bloomberg.com/news/articles/2015-05-11/oil-rises-as-saudi-arabia/',
            'https://marketwatch.com/story/nasdaq-closes-above-5000-for-the-first-time/',
            'https://marketwatch.com/story/heres-what-happens-to-interest-rates/',
            'https://investopedia.com/terms/s/stockmarket.asp',
            'https://investopedia.com/terms/e/etf.asp',
            'https://morningstar.com/articles/693218/does-the-4-rule-work-for-early-retirees',
            'https://moneycontrol.com/stocks/marketstats/nsegainer/index.php',
            'https://bankrate.com/taxes/tax-return-status/',
            'https://nerdwallet.com/blog/credit-cards/best-credit-cards/',
            'https://creditkarma.com/credit-cards/i/rewards-credit-cards',
            'https://nasdaq.com/article/oil-price-decline-hits-inflation',
            'https://bloomberg.com/news/articles/2015-05-12/greece-talks/',
            'https://forbes.com/sites/samanthasharf/2015/05/12/the-best-places/',
            'https://marketwatch.com/story/dow-closes-above-18000/',
            'https://investopedia.com/terms/i/indexfund.asp',
            'https://morningstar.com/articles/741555/the-bucket-approach-to-retirement',
            'https://nasdaq.com/symbol/tsla',
            'https://nasdaq.com/symbol/fb',
            'https://nasdaq.com/article/why-did-apple-stock-drop',
            'https://bloomberg.com/news/articles/2015-05-11/ecb-signals-bond/',
            'https://investopedia.com/terms/d/dividend.asp',
        ],

        // ── TRAVEL persona ───────────────────────────────────────────────────
        travel: [
            'https://tripadvisor.com/Restaurant_Review-g30373-d326655-Reviews-Bob_Sykes_Barbeque.html',
            'https://tripadvisor.com/Hotel_Review-g298184-d301416-Reviews-Bali_Mandira.html',
            'https://tripadvisor.com/Attraction_Review-g187791-d190275-Reviews-Eiffel_Tower.html',
            'https://tripadvisor.com/Tourism-g60763-New_York_City_New_York-Vacations.html',
            'https://tripadvisor.com/Restaurants-g60763-New_York_City_New_York.html',
            'https://tripadvisor.com/Hotel_Review-g60763-d93589-Reviews-The_Plaza.html',
            'https://tripadvisor.com/Attraction_Review-g60763-d105101-Reviews-Metropolitan.html',
            'https://expedia.com/New-York-Hotels.d178293.Travel-Guide-Hotels',
            'https://expedia.com/Paris-Hotels.d179898.Travel-Guide-Hotels',
            'https://expedia.com/London-Hotels.d178279.Travel-Guide-Hotels',
            'https://kayak.com/flights',
            'https://kayak.com/hotels',
            'https://priceline.com/hotels/',
            'https://hotels.com/search.do?q-destination=London',
            'https://skyscanner.com/flights',
            'https://lonelyplanet.com/france/paris',
            'https://lonelyplanet.com/italy/rome',
            'https://lonelyplanet.com/japan/tokyo',
            'https://lonelyplanet.com/indonesia/bali',
            'https://transatholidays.com/',
            'https://visit-montenegro.com/tourism-mi.htm',
            'https://tripadvisor.com/Attractions-g294217-Activities-India.html',
            'https://expedia.com/Thailand-Hotels.d178298.Travel-Guide-Hotels',
            'https://tripadvisor.com/Tourism-g187791-Paris_Ile_de_France-Vacations.html',
            'https://tripadvisor.com/Tourism-g298184-Bali-Vacations.html',
            'https://lonelyplanet.com/australia/sydney',
            'https://lonelyplanet.com/morocco/marrakesh',
            'https://skyscanner.com/hotels',
            'https://kayak.com/cars',
            'https://hotels.com/search.do?q-destination=Paris',
        ],

        // ── NEWS persona ─────────────────────────────────────────────────────
        news: [
            'https://nytimes.com/keyword/carla-bley',
            'https://edition.cnn.com/2009/SPORT/football/10/18/africa.ghana.nigeria/index.html',
            'https://money.cnn.com/magazines/fortune/fortune_archive/1988/01/04/70037/index.htm',
            'https://articles.latimes.com/keyword/glenn-davis',
            'https://nytimes.com/section/technology',
            'https://nytimes.com/section/science',
            'https://nytimes.com/section/health',
            'https://edition.cnn.com/world',
            'https://edition.cnn.com/science',
            'https://edition.cnn.com/health',
            'https://washingtonpost.com/technology/',
            'https://washingtonpost.com/world/',
            'https://theguardian.com/world',
            'https://theguardian.com/science',
            'https://theguardian.com/technology',
            'https://bbc.com/news/world',
            'https://bbc.com/news/science_and_environment',
            'https://bbc.com/news/technology',
            'https://reuters.com/technology/',
            'https://reuters.com/world/',
            'https://apnews.com/hub/technology',
            'https://apnews.com/hub/science',
            'https://apnews.com/hub/health',
            'https://theatlantic.com/science/',
            'https://theatlantic.com/technology/',
            'https://thehill.com/policy/technology',
            'https://vox.com/science-and-health',
            'https://axios.com/science',
            'https://politico.com/news/technology',
            'https://nbcnews.com/science',
        ],
    },

    // ── Runtime state ─────────────────────────────────────────────────────────
    _recentlyUsed: {},   // per-persona recent picks (anti-repeat)
    _deadUrls:     null, // Set loaded from chrome.storage.local

    // ── Load persisted dead-URL blacklist from storage ────────────────────────
    async loadDeadUrls() {
        return new Promise((resolve) => {
            chrome.storage.local.get('deadUrls', (data) => {
                this._deadUrls = new Set(data.deadUrls || []);
                console.log(`[DCG SiteSelector] Loaded ${this._deadUrls.size} dead URLs from storage.`);
                resolve();
            });
        });
    },

    // ── Permanently blacklist a dead URL ──────────────────────────────────────
    markDead(url) {
        if (!this._deadUrls) this._deadUrls = new Set();
        if (this._deadUrls.has(url)) return;

        this._deadUrls.add(url);
        const arr = [...this._deadUrls];
        chrome.storage.local.set({ deadUrls: arr });
        console.log(`[DCG SiteSelector] Marked dead (${this._deadUrls.size} total): ${url}`);
    },

    // ── Pick a fresh dataset URL for the given persona ────────────────────────
    getSiteForCategory(category) {
        const pool   = this.sites[category] || this.sites['news'];
        const dead   = this._deadUrls || new Set();
        const recent = this._recentlyUsed[category] || [];

        // Exclude blacklisted + recently-used URLs
        let available = pool.filter(u => !dead.has(u) && !recent.includes(u));

        // If all remaining URLs have been used recently, relax only the recent filter
        if (available.length === 0) {
            available = pool.filter(u => !dead.has(u));
        }

        // If everything is blacklisted fall back to Wikipedia
        if (available.length === 0) {
            console.warn(`[DCG SiteSelector] All ${category} URLs are dead — using fallback.`);
            return this.getFallback(category);
        }

        const chosen = available[Math.floor(Math.random() * available.length)];
        this._recentlyUsed[category] = [...recent, chosen].slice(-10);

        // Strip path and query to return only the main page (root domain)
        try {
            const urlObj = new URL(chosen);
            return urlObj.origin + '/';
        } catch (e) {
            return chosen;
        }
    },

    // ── Get a guaranteed-safe fallback URL (Wikipedia) ────────────────────────
    getFallback(category) {
        const pool    = FALLBACK_URLS[category] || FALLBACK_URLS['news'];
        const recent  = this._recentlyUsed[`__fallback_${category}`] || [];
        let available = pool.filter(u => !recent.includes(u));
        if (available.length === 0) {
            this._recentlyUsed[`__fallback_${category}`] = [];
            available = pool;
        }
        const chosen = available[Math.floor(Math.random() * available.length)];
        this._recentlyUsed[`__fallback_${category}`] = [...recent, chosen].slice(-5);
        return chosen;
    },
};
